Block-Equity/stellar-android-wallet

app/src/main/AndroidManifest.xml
app/src/main/java/blockeq/com/stellarwallet/activities/CreateWalletActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/LoginActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/res/drawable/background_item_view_phrase_word.xml
app/src/main/res/layout/activity_create_wallet.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_recover_wallet.xml
app/src/main/res/layout/item_view_phrase_word.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Restore phrase

---

app/src/main/java/blockeq/com/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/res/layout/activity_recover_wallet.xml
app/src/main/res/values/strings.xml

- Check word count for 12 or 24
- Displays an invalid message in red if word count doesn't match
- Sends the entered mnemonic to `PinActivity.kt`

Recover mnemonic phrase

---

app/build.gradle
app/src/main/java/blockeq/com/stellarwallet/activities/LoginActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/LocalStore.kt
app/src/main/res/layout/activity_recover_wallet.xml
app/src/main/res/values/strings.xml
build.gradle

- Add generate wallet function in PinActivity
- Stores only the [accountId](https://www.stellar.org/developers/guides/concepts/accounts.html#account-id) of the stellar account, which is the public key

Generate stellar address

---

app/src/main/AndroidManifest.xml
app/src/main/java/blockeq/com/stellarwallet/activities/LoginActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/MainActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/LocalStore.kt

- Prompts the PIN
- Regenerates the stellar `KeyPair` and fetches the account from horizon
- Stores fetched account balances object in shared preferences `KEY_STELLAR_BALANCES_KEY`
- Wipes user data if pin is entered incorrectly 3 times

Check login pin

---

app/src/main/java/blockeq/com/stellarwallet/activities/LoginActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/LocalStore.kt

- Refactor the key generation logic to an Async Task so the main thread is not stalled

Improve login flow

---

app/src/main/AndroidManifest.xml
app/src/main/java/blockeq/com/stellarwallet/activities/InflationActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/SendActivity.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/AssetsRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/Constants.kt
app/src/main/java/blockeq/com/stellarwallet/interfaces/OnSendPayment.kt
app/src/main/java/blockeq/com/stellarwallet/interfaces/SuccessErrorCallback.kt
app/src/main/java/blockeq/com/stellarwallet/services/networking/Horizon.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt
app/src/main/res/layout/activity_inflation.xml
app/src/main/res/layout/content_enter_address.xml
app/src/main/res/layout/contents_send.xml
app/src/main/res/values/strings.xml

- Added ability to set inflation destination (default to lumenaut's `GCCD6AJOYZCUAQLX32ZJF2MKFFAUJ53PVCFQI3RHWKL3V47QYE2BNAUT`)
- Shows error if minimum balance is below 1 xlm
- I've also been refactoring some things as I come across, for example renaming the SendPayments interface to be more abstract (any success and failure callback)
- Adding util functions like getBalance(type: String) to prepare for near future PRs when we'll refer to a `currentAsset` field to know which one we're displaying in the wallet

Set Inflation

---

app/src/main/java/blockeq/com/stellarwallet/activities/AssetsActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/InflationActivity.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/AssetsRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/Constants.kt
app/src/main/java/blockeq/com/stellarwallet/interfaces/RecyclerViewListener.kt
app/src/main/java/blockeq/com/stellarwallet/models/SupportedAsset.kt
app/src/main/java/blockeq/com/stellarwallet/services/networking/Horizon.kt
app/src/main/res/layout/content_assets_activity.xml
app/src/main/res/values/strings.xml

- Now you can `add` and `remove` trust lines on Android!
- UI shows progress bar on loading
- Views are updated on completion

Trustline Operation

---

app/src/main/java/blockeq/com/stellarwallet/WalletApplication.kt
app/src/main/java/blockeq/com/stellarwallet/activities/EnterAddressActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/SendActivity.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/AssetsRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/WalletRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/Constants.kt
app/src/main/java/blockeq/com/stellarwallet/models/UserSession.kt
app/src/main/java/blockeq/com/stellarwallet/models/WalletHeterogenousArray.kt
app/src/main/java/blockeq/com/stellarwallet/services/networking/Horizon.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt
app/src/main/java/blockeq/com/stellarwallet/utils/StringFormat.kt
app/src/main/res/layout/contents_send.xml
app/src/main/res/values/strings.xml

- THE APP IS NOW FULLY FUNCTIONAL!!! You can now switch assets and send them!!! 🙌 🎉 
- I'm currently storing `currAssetCode` `currAssetName` and `currAssetIssuer` as variables in WalletApplication.kt, would it be better if they were encapsulated in some "currentAsset" object that lets you access them or is that not needed? (That class probably won't be used again)
- Working through the app I have identified more bugs / refactor opportunities / things I forgot to implement. So I added them to the board.

Switch Assets UI

---

app/src/main/java/blockeq/com/stellarwallet/services/networking/Horizon.kt

- Sending payments now takes into account whether the account needs to be first created or not.
- Tested it ✅

Add create account functionality

---

app/build.gradle
app/src/main/java/blockeq/com/stellarwallet/activities/AssetsActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/ViewSecretSeedActivity.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/Constants.kt
app/src/main/java/blockeq/com/stellarwallet/interfaces/OnLoadAccount.kt
app/src/main/java/blockeq/com/stellarwallet/services/networking/Horizon.kt
app/src/main/res/layout/activity_recover_wallet.xml
app/src/main/res/layout/activity_show_mnemonic.xml
app/src/main/res/layout/activity_view_secret_seed.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/fragment_wallet.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

* Makes more user input checks for mnemonic (only allows alphabetic characters and spaces)
* Also trims the start and end of the mnemonic phrase
* Added a text for no transactions if there are no transactions on the account

Beta release

---

app/src/main/java/blockeq/com/stellarwallet/activities/AssetsActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/InflationActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/SendActivity.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/AssetsRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/SettingsFragment.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/LocalStore.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/WalletLifecycleListener.kt
app/src/main/java/blockeq/com/stellarwallet/interfaces/ChangeTrustlineListener.kt
app/src/main/java/blockeq/com/stellarwallet/interfaces/CheckPinListener.kt
app/src/main/java/blockeq/com/stellarwallet/models/UserSession.kt
app/src/main/java/blockeq/com/stellarwallet/models/WalletHeterogeneousArray.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt
app/src/main/res/layout/activity_inflation.xml
app/src/main/res/layout/contents_send.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values/strings.xml

Urgent
* Caches PIN on `UserSession` and is wiped on app going to the background (paused)
* Doesn't request PIN for inflation and change trustline

Pin settings

---

app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/SendActivity.kt
app/src/main/res/values/strings.xml

Urgent
* Update PIN view text to let user know how many attempts are left before wipe.
* Added a 1 second delay after transaction is sent to make the animation smoother (Also helps with the data updating instead of user waiting on it).

Show attempts pin

---

app/src/main/java/blockeq/com/stellarwallet/activities/BaseActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/SendActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/ShowMnemonicActivity.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/BaseFragment.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/LocalStore.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/PassphraseDialogHelper.kt
app/src/main/java/blockeq/com/stellarwallet/models/PinViewState.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt
app/src/main/res/layout/activity_recover_wallet.xml
app/src/main/res/layout/activity_show_mnemonic.xml
app/src/main/res/layout/passphrase_dialog.xml
app/src/main/res/values/strings.xml

High
* Adds the `advanced security` option to apply a passphrase on top of the existing mnemonic to generate the `KeyPair` for the stellar account
* Fully tested for creating and restoring passphrase on mobile and other clients. And vice versa.

Passphrase support

---

README.md
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/AssetsRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/WalletRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt
app/src/main/java/blockeq/com/stellarwallet/utils/NetworkUtils.kt
app/src/main/java/blockeq/com/stellarwallet/utils/StringFormat.kt
app/src/main/res/layout/activity_pin.xml
app/src/main/res/values/strings.xml

Normal
* Update documentation of README, consistent naming within the app
* Add comments for structure of app
Adding this here for the readme

Documentation

---

app/build.gradle
app/src/main/java/blockeq/com/stellarwallet/WalletApplication.kt
app/src/main/java/blockeq/com/stellarwallet/activities/AssetsActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/BalanceSummaryActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/BaseActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/EnterAddressActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/InflationActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/LoginActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/MainActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/ReceiveActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/SendActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/ShowMnemonicActivity.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/AssetsRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/adapters/WalletRecyclerViewAdapter.kt
app/src/main/java/blockeq/com/stellarwallet/encryption/KeyStoreWrapper.kt
app/src/main/java/blockeq/com/stellarwallet/flowcontrollers/PinFlowController.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/BaseFragment.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/SettingsFragment.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/blockeq/com/stellarwallet/helpers/LocalStore.kt
app/src/main/java/blockeq/com/stellarwallet/models/UserSession.kt
app/src/main/java/blockeq/com/stellarwallet/services/networking/Horizon.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt
build.gradle

Low
upgrading kotlin from 1.2.50 to 1.2.71, removing the static instance of context from application class, making WalletApplicatoin.localStore not nullable with lateinit, supressing a safe @Suppress("UNCHECKED_CAST"), removing the setupUi () { throw IllegalStateException("Please override this function.") } from baseActivity, ...

basic clean up

---

app/src/androidTest/java/blockeq/com/stellarwallet/ApplicationEspressoTest.kt
app/src/main/AndroidManifest.xml

Urgent
fixes #59 disabling RTL support since the mnemonic words are not being rendered.

disabling rtl support

---

app/src/main/java/blockeq/com/stellarwallet/WalletApplication.kt
app/src/main/java/blockeq/com/stellarwallet/encryption/PRNGFixes.java

fixes #70 adding a ssl patch and PRNGSecureRandom as recommended on htps://android-developers.googleblog.com/2013/08/some-securerandom-thoughts.html

Patching the random generator with a high entropy

---

app/build.gradle
app/lint-baseline.xml
app/src/main/java/blockeq/com/stellarwallet/activities/ViewSecretSeedActivity.kt
app/src/main/java/blockeq/com/stellarwallet/reusables/views/CustomSelector.kt

fixes #72, adding base lint xml and getting ready to have a proper builds checks

lint baseline file to pass build check

---

app/src/androidTest/java/blockeq/com/stellarwallet/utils/AccountUtilsTest.java

adding basic unit tests for the creation of the encrypted phrase and passphrase.

unit tests around encrypted pneumonic phrase `AccountUtils`

---

app/src/main/java/blockeq/com/stellarwallet/activities/BaseActivity.kt

Urgent
* Double check if the stellar account id exists before requesting login
* Clears user data if otherwise to clean up state of the wallet

Login Check Bug

---

app/src/androidTest/java/blockeq/com/stellarwallet/encryption/KeyStoreWrapperTest.kt
app/src/main/java/blockeq/com/stellarwallet/activities/BaseActivity.kt
app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/encryption/KeyStoreWrapper.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt

Urgent
* Refactor clearing data code into an AccountUtils method, instead of using LocalStore.clear

Add AccountUtils.wipe() method instead of localstore.clear()

---

app/src/androidTest/java/blockeq/com/stellarwallet/encryption/KeyStoreWrapperTest.kt
app/src/androidTest/java/blockeq/com/stellarwallet/utils/AccountUtilsTest.java
app/src/main/java/blockeq/com/stellarwallet/helpers/LocalStore.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt

removing the usage of String.join since is having some issues in bitrise, looks like is a Java 8 method. Instead I used the TextUtils.join that is android specific.

making CI to work with instrumentation tests

---

app/src/androidTest/java/blockeq/com/stellarwallet/LaunchPage.kt
app/src/androidTest/java/blockeq/com/stellarwallet/RecoveryWalletPage.kt
app/src/androidTest/java/blockeq/com/stellarwallet/WalletCreationTest.kt
app/src/main/java/blockeq/com/stellarwallet/activities/ShowMnemonicActivity.kt

Fix issue52

---

CHANGELOG.md
app/build.gradle
app/src/main/java/blockeq/com/stellarwallet/activities/WalletActivity.kt
app/src/main/res/menu/navigation.xml

Merging dev -> master 1.0.4.1

---

app/build.gradle
app/src/main/java/blockeq/com/stellarwallet/helpers/PassphraseDialogHelper.kt
app/src/main/res/values/strings.xml

High
* Changes version code to 18
* Changes no transactions text to remove "Start trading" since we don't support it yet.
* Prevents passphrase empty, fixes issue #95

Review changes for release 1.0.4.2

---

app/src/main/java/blockeq/com/stellarwallet/activities/ShowMnemonicActivity.kt
app/src/main/java/blockeq/com/stellarwallet/utils/AccountUtils.kt

Fix issue #98

---

app/src/main/AndroidManifest.xml
app/src/main/java/blockeq/com/stellarwallet/activities/DiagnosticActivity.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/SettingsFragment.kt
app/src/main/java/blockeq/com/stellarwallet/utils/DiagnosticUtils.kt
app/src/main/java/blockeq/com/stellarwallet/utils/StringFormat.kt
app/src/main/res/drawable/bg_edit_text.xml
app/src/main/res/layout/activity_diagnostic.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values/strings.xml

Email diagnostic tool

---

app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
app/src/main/java/blockeq/com/stellarwallet/fragments/SettingsFragment.kt
app/src/main/java/blockeq/com/stellarwallet/models/PinViewState.kt

fixes #103, asking for the pin when the user tries to enable / disable the request pin when sending payments

#103_request_pin_when_changing_security_settings

---

app/build.gradle
app/src/main/java/com/blockeq/stellarwallet/WalletApplication.kt

adding leak canary for the debug builds.

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/blockeq/stellarwallet/activities/WebViewActivity.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/SettingsFragment.kt
app/src/main/java/com/blockeq/stellarwallet/utils/DiagnosticUtils.kt
app/src/main/res/layout/activity_web_view.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values/strings.xml

Normal
* Adds privacy policy and terms of service to the app
Resolves #114

Add About section to settings

---

app/src/main/java/com/blockeq/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/SettingsFragment.kt
app/src/main/java/com/blockeq/stellarwallet/helpers/OnTextChanged.kt
app/src/main/java/com/blockeq/stellarwallet/helpers/StellarRecoveryString.kt
app/src/main/res/layout/activity_recover_wallet.xml

High
* Highlights incorrect words against the BIP39 english word list
* Also highlights the stellar seed recovery string in red if it is invalid

Bip39 mnemonic spellcheck

---

app/src/main/java/com/blockeq/stellarwallet/activities/AssetsActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/DiagnosticActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/EnterAddressActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/MnemonicActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/PinActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/java/com/blockeq/stellarwallet/helpers/Constants.kt
app/src/main/java/com/blockeq/stellarwallet/models/Diagnostic.kt
app/src/main/java/com/blockeq/stellarwallet/models/Fields.kt
app/src/main/java/com/blockeq/stellarwallet/utils/AccountUtils.kt
app/src/main/res/layout/activity_diagnostic.xml
app/src/main/res/values/strings.xml

High
* The spec as detailed in #127 
* Product discussions are in https://airtable.com/tbltVhiXxomHljBxX/viwzllQDutDx2SJVI/recbi6YB6aULADBK0

Diagnostic Tool for Android - v2.1

---

app/schemas/com.blockeq.stellarwallet.vmodels.ExchangesRoomDatabase/1.json
app/src/androidTest/java/com/blockeq/stellarwallet/LaunchPage.kt
app/src/androidTest/java/com/blockeq/stellarwallet/WalletCreationTest.kt
app/src/main/java/com/blockeq/stellarwallet/WalletApplication.kt
app/src/main/java/com/blockeq/stellarwallet/activities/SendActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/WalletActivity.kt
app/src/main/java/com/blockeq/stellarwallet/adapters/TradingPagerAdapter.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/TradingFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/MyOffersTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/OrderBookTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnTradeCurrenciesChange.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnTradeCurrenciesChanged.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnUpdateTradingCurrencies.kt
app/src/main/java/com/blockeq/stellarwallet/models/AssetUtil.kt
app/src/main/java/com/blockeq/stellarwallet/models/ExchangeMapper.kt
app/src/main/java/com/blockeq/stellarwallet/models/TradingPair.kt
app/src/main/java/com/blockeq/stellarwallet/utils/KeyboardUtils.java
app/src/main/java/com/blockeq/stellarwallet/vmodels/ExchangeEntity.kt
app/src/main/java/com/blockeq/stellarwallet/vmodels/ExchangeProvider.kt
app/src/main/java/com/blockeq/stellarwallet/vmodels/ExchangeRepository.kt
app/src/main/java/com/blockeq/stellarwallet/vmodels/ExchangeViewModel.kt
app/src/main/java/com/blockeq/stellarwallet/vmodels/ExchangesRoomDatabase.kt
app/src/main/java/com/blockeq/stellarwallet/vmodels/TradingViewModel.kt
app/src/main/res/layout/fragment_tab_my_offers.xml
app/src/main/res/layout/fragment_tab_trade.xml

Trading asset selection logic

---

app/src/androidTest/java/com/blockeq/stellarwallet/LaunchPage.kt
app/src/androidTest/java/com/blockeq/stellarwallet/ReceivePage.kt
app/src/androidTest/java/com/blockeq/stellarwallet/RecoveryWalletPage.kt
app/src/androidTest/java/com/blockeq/stellarwallet/SettingsPage.kt
app/src/androidTest/java/com/blockeq/stellarwallet/ViewSecretSeedPage.kt
app/src/androidTest/java/com/blockeq/stellarwallet/WalletCreationTest.kt
app/src/androidTest/java/com/blockeq/stellarwallet/WalletPage.kt
app/src/androidTest/java/com/blockeq/stellarwallet/WalletRecoveryTest.kt

Normal
* Add recovery tests for the following test cases:
- I'm able to recover a wallet using a 12 word mnemonic
- I'm able to recover a wallet using a 12 word mnemonic and passcode
- I'm able to recover a wallet using a 24 word mnemonic
- I'm able to recover a wallet using a 24 word mnemonic and passcode
- I'm able to recover a wallet using a 56 character secret seed

Recovery wallet ui tests

---

app/src/androidTest/java/com/blockeq/stellarwallet/utils/AccountUtilsTest.java
app/src/main/java/com/blockeq/stellarwallet/activities/PinActivity.kt
app/src/main/java/com/blockeq/stellarwallet/helpers/LocalStore.kt
app/src/main/java/com/blockeq/stellarwallet/utils/AccountUtils.kt

High
* Removes all TODOs and Deprecated methods related to the Old wallet passphrase logic
* Also removes all logic that checks for the old wallet and related code

Remove deprecated methods and variables

---

app/src/main/java/com/blockeq/stellarwallet/fragments/TradingFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/OrderBookTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnUpdateOrderBook.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnUpdateTradeTab.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnUpdateTradingCurrencies.kt

market order feature under tradeTabFragment.

---

app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt

fixing the order market offer where the price sent was the buying amount.

trading bug fixing

---

app/src/main/java/com/blockeq/stellarwallet/activities/DiagnosticActivity.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/SettingsFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/MyOffersTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/OrderBookTabFragment.kt

fixing the email to send the diagnostics and hiding debug preferences in a non debug builds.

bugbash fixes

---

app/src/main/java/com/blockeq/stellarwallet/adapters/OrderBooksAdapter.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/MyOffersTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/OrderBookTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/models/Currency.kt
app/src/main/java/com/blockeq/stellarwallet/models/HorizonException.kt
app/src/main/java/com/blockeq/stellarwallet/models/SelectionModel.kt
app/src/main/java/com/blockeq/stellarwallet/remote/Horizon.kt
app/src/main/res/layout/fragment_tab_trade.xml
app/src/main/res/layout/view_custom_selector.xml
app/src/main/res/values/strings.xml

disabling pull to refresh in order book fragment, changing the amount form float to double in tradeTabfragment to show 7 decimals, ...

minor bugfixing android

---

app/src/main/java/com/blockeq/stellarwallet/activities/SendActivity.kt
app/src/main/java/com/blockeq/stellarwallet/remote/Horizon.kt

adding a generic error message for any HorizonException while sending funds.

generic error message sending funds

---

app/src/main/java/com/blockeq/stellarwallet/activities/EnterAddressActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/SendActivity.kt
app/src/main/java/com/blockeq/stellarwallet/adapters/MyOffersAdapter.kt
app/src/main/java/com/blockeq/stellarwallet/adapters/WalletRecyclerViewAdapter.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/MyOffersTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/models/UserSession.kt
app/src/main/res/layout/fragment_tab_trade.xml
app/src/main/res/layout/row_my_offers.xml
app/src/main/res/values/strings.xml

setting 7 decimals max to sendACtivity and Enter AddressActivity and setting the LMX availables in trading view.

decimals in sending journey and available LMX in tradeView

---

app/src/main/java/com/blockeq/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt

it fixes #172, sending empty as buying price was crashing horizon.

GH-172-NumberFormatException with empty buying price

---

app/lint.xml
app/src/main/java/com/blockeq/stellarwallet/activities/RecoverWalletActivity.kt
app/src/main/java/com/blockeq/stellarwallet/adapters/ContactViewHolder.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/ContactsFragment.kt
app/src/main/java/com/blockeq/stellarwallet/helpers/OnTextChanged.kt
app/src/main/java/com/blockeq/stellarwallet/views/RecyclerSectionItemDecoration.kt
app/src/main/res/drawable/white_ripple_background.xml
app/src/main/res/layout/fragment_contact_list.xml
app/src/main/res/layout/item_contact.xml
app/src/main/res/layout/item_sticky_header_contact.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

cleaning some null checks in contactfragment.kt, removing the flickering in item_contact.xml

contacts improvements

---

app/src/main/java/com/blockeq/stellarwallet/vmodels/ContactsRepositoryImpl.kt

no contacts state was broken because contactRepository did not send empty list contact to the ui.

sending empty list form contactrepository to the ui.

---

app/src/main/java/com/blockeq/stellarwallet/activities/AssetsActivity.kt
app/src/main/java/com/blockeq/stellarwallet/activities/WalletActivity.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/res/menu/navigation.xml
app/src/main/res/values/strings.xml

fixes #192, adding dialog in the tradeFragment when there are not enough currency pairs.

trading error dialog

---

app/src/main/java/com/blockeq/stellarwallet/fragments/ContactsFragment.kt
app/src/main/res/layout/fragment_contact_list.xml
app/src/main/res/menu/contacts_fragment_menu.xml
app/src/main/res/values/strings.xml

adding dialog to invite the user to go to settings when the permissions are muted.

permissions muted dialog

---

app/src/main/java/com/blockeq/stellarwallet/adapters/WalletRecyclerViewAdapter.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/com/blockeq/stellarwallet/mvvm/effects/EffectsRepository.kt
app/src/main/java/com/blockeq/stellarwallet/mvvm/effects/WalletViewModel.kt

recovering the streaming support.

---

app/src/main/java/com/blockeq/stellarwallet/adapters/OrderBooksAdapter.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/MyOffersTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/OrderBookTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/remote/Horizon.kt

Refactoring and fixing orderbook list and adapter/.

---

app/src/main/java/com/blockeq/stellarwallet/fragments/TradingFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/mvvm/effects/EffectsRepository.kt
app/src/main/java/com/blockeq/stellarwallet/mvvm/effects/WalletViewModel.kt

fix the order book where the data was displayed backwards buying vs selling.

fixing order book

---

app/src/main/java/com/blockeq/stellarwallet/adapters/OrderBooksAdapter.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/TradingFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/WalletFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/MyOffersTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/OrderBookTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/fragments/tabs/TradeTabFragment.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnRefreshOrderBookListener.kt
app/src/main/java/com/blockeq/stellarwallet/interfaces/OnUpdateOrderBook.kt
app/src/main/java/com/blockeq/stellarwallet/remote/Horizon.kt
app/src/main/res/layout/fragment_tab_order_book.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/blockeq/stellarwallet/KotlinClassRoom.kt

adding empty text for orderbook failed to fetch.
